# News

2024-12-16. I am visiting Georgetown University and the National Cancer Institute in the Washington, DC area during the winter break. 

2024-12-04. I have presented an invited talk at International Symposium on Theories, Methodologies and Applications for Large Complex Data, at Tsukuba, Japan, on Dec. 4-6. 

2024-11-28. Congratulations to Dr. Minwoo Kim, who has successfully defended his PhD thesis "Enhancing statistical utility in private multivariate statistics: Forcusing on contingency tables and principal component analysis."

2024-11-14. I gave a keynote speech at the JMP Discovery Summit Korea 2024 and am making [the slides](./papers/Data_Literacy.pdf) I used publicly available.

2024-10-24. I am happy to announce that an UTFORSK grant from Norwegian Directorate for Higher Education and Skills is awarded for the full four years of 2025--2028. This project is to increase research and education activities in [Statistics of Complex Data (ScoDa)](https://espresso.diku.no/projects/?2&project=UTF-2024/10203) and is a joint grant between Universitetet i Stavanger (Professor Joern Schulz as PI) and SNU, as the main foreign partner. 

2024-10-17. I am actively participating in the Interactions of Geometry and Statistics [(ISAG) II workshop](pictures/Group-2-22.10.2024-Yes.jpg), IMS, NUS, in Singapore from Oct. 17 to Oct. 25. 

2024-10-16. I gave [a talk on Differential Privacy](https://youtu.be/wXpMeDbogd4?si=2rwnXShalUhwPctE) at the Privacy Future Forum, hosted by Personal Information Protection Commission.  

2024-09-08. I gave a talk on Privacy Enhancing Technologies at the 13th National Statistics Development Forum. 

2024-09-01. Welcome Jaeeun, Wooyeol and Jihyun to my lab!

2024-09-01. I am serving as an associate chair for the statistics department, SNU. 

2024-07-18. I am visiting the National Cancer Institute in the Washington, DC area during my summer break. 

2024-06-21. Congratulations to Dr. Donghyeok Jo, who has successfully defended his PhD thesis "Advances on Statistical Inferences for Riemannian Manifold-valued Data."

2024-06-12. Congratulations to Dr. Sujin Lee, who has successfully defended her PhD thesis "Variable Selection and Inference Strategies for Compositional Regressions."

2024-06-03. A research article, coauthored with David, Armin and my previous PhD advisee Brian, on averaging SPD matrices is now accepted for publication in *Bernoulli*, after six years of effort! Check out the preprint at  [arXiv](https://arxiv.org/abs/2306.12025). 

2024-05-31. Congratulations to Dr. Sangil Han, who has successfully defended his PhD thesis "Advances in supervised and unsupervised dimension reduction."

2024-05-30. [I](pictures/2024-05-30-PET-Forum.jpg) gave an invited talk at the first PET Forum seminar of 2024, hosted by [Personal Information Protection Commission](https://www.pipc.go.kr/eng/user/ltn/new/newsDetail.do?nttId=2531) on AI-based synthetic data generation. 

2024-05-27. I have been selected to receive a five-year mid-career research grant from the National Research Foundation of Korea (RS-2024-00333399).

2024-05-14. A research article on a principal component analysis for compositional data, coauthored with Jaesung and Dr. Kipoong Kim, is accepted for a publication in *CSDA*. This works uses the framework of generalized Frechet means to evaluate the asymptotic properties of the "compositional subspace" estimators. 

2024-04-01. Welcome Dr. Soyul Han to my lab! 

2024-04-01. Sujin's work, comparing the debiasing-based and resampling-based inference procedures for multiple compositional regression problems, is accepted for a publication in *ChemLab*. Congratulations to Sujin!

2024-03-04. I am very happy to announce that the **Institute for Data Innovation in Science** (IDIS) at Seoul National University is now established, and I am appointed as the director of the institute. The core mission of IDIS is to spearhead data-driven innovation across all scientific domains, leveraging data to tackle intricate scientific hurdles, advance scientific frontiers, and foster societal progress. 

2024-02-29. A research article on double data piling for multi-category classification, co-authored with former students Taehyun and Woonyoung, is accepted for a publication in *Journal of Korean Statistical Society*. This will be my first JKSS paper. 

2024-02-16. Some great news to share. Dr. Seung Woo Kwak is now a professor at Sungkonghoe University; Dr. Kipoong Kim is now a professor at Changwon National University. Congratulations! I welcome new members to the lab: Graduate students Seongjae, Jeehyun and Chihoon have joined my lab. Dr. Yangha Chung has also joined for the SSTF project.  

2024-02-02. Dr. Kwak's work on differentially private contingency table analysis is accepted for publication in *Stat*. [(link)](https://doi.org/10.1002/sta4.658)  

2024-01-20. The research article "Robust SVD Made Easy" is accepted for a poster presentation in AISTATS 2024. Congratulations to Sangil and Kyoowon! [(arXiv)](https://arxiv.org/abs/2402.09754)

2023-12-13. [Closed] I have an opening for a [postdoctoral researcher](./papers/Wanted.html). 

2023-12-13. Sangil and Minwoo's work on sparse ordinal discriminant analysis is now accepted for publication in *Biometrics*. This work adopts the optimal scoring method, tailored to reflect ordinal responses, with a sparsity enforcing penalization, and provides an accurate and easy-to-interpret discriminant basis in high-dimensions. 

2023-10-23. Changjo's research on an application of TDA to data on the torus has been accepted for publication in *Stat*. Congratulations to Changjo! 

2023-10-18. I am happy to announce that the natural science LAMP project team at SNU is awarded the five-year LAMP project. This project supports data-based discovery in all areas of natural sciences. Planned activities include founding "Data Discovery Science Research Institute," a new research institute at SNU formed by expanding Statistical Research Institute. [(post)](https://www.snu.ac.kr/snunow/press?md=v&bbsidx=143708) [(news)](https://www.veritas-a.com/news/articleView.html?idxno=474831)

2023-10-05. [Kipoong's work on Integrative Sparse Reduced-Rank Regression](https://doi.org/10.1007/s11222-023-10322-3) is now accepted for publication in *Statistics and Computing*. 

2023-09-06. A research article, titled "Comparisons of parametric and non-parametric methods for analyzing RT-PCR experiment data" is accepted for publication in *ChemLab*. This paper demonstrates the advantage in using proper permutation tests in small-sample experiments.  [(link)](https://www.sciencedirect.com/science/article/pii/S0169743923002320)

2023-09-05. A series of lecture videos on multivariate statistics, recorded in 2021, is now posted on [YouTube](https://www.youtube.com/watch?v=UdiIolIT3HU&list=PLXgVK0KVZjzMMnCZmZR6DmPsp5ResfZxg)

2023-09-01. Welcome DongSun Yoon to the lab.

2023-08-30. Presented about Privacy Enhancing Technologies at the 12th national statistics development forum, organized by Statistics Korea.

2023-07-02. Gave a talk on James-Stein eigenvector estimators at ECOSTA conference, Tokyo, Japan. 

2023-06-01. Our research team, consisting of Dr. Ahn, Dr. Park, Dr. Kim, and myself, has been awarded a prestigious three-year Basic Research Lab grant. The grant is specifically designated for conducting research in the field of Data Privacy for Statistical Machine Learning.

2023-02-24. Featured in a [YouTube clip](https://youtu.be/s9aOZDLAc9M).

2023-02-21. I gave an [AI & Natural Sciences seminar](https://www.kias.re.kr/kias/activities/seminars/view.do?seqno=PGN1720230130-0002&menuNo=404003&schoolsCd=CP&centrspgmsCd=&sdate=2023-01-13&edate=&mjrcdnm=&searchCnd=1&searchWord=&pageIndex=1) at  Korea Institute for Advanced Study (KIAS) on Feb 21, 2023. 

2023-01-26. I gave an [invited lecture](./pictures/2023_1_KDAS_invited_lecture.jpg) at the winter conference of [the Korean Data Analysis Society](http://www.kdas.or.kr), which was held in person on Jan 26-27, 2023, in Pusan, Korea.

2022-11-15. My first popular science book, [*Data literacy over mathematics*](./books.html)  (title translated from Korea, the book is written in Korean)  is now on [sale](https://product.kyobobook.co.kr/detail/S000200243265). I thank the editor, the publisher, and my family for their enormous support.  

2022-10-04. Sujin's [work](./papers/SMMR_R2.pdf) on resampling-based inference tools for compositional regression will appear in SMMR. Congratulations to Sujin!

2022-09-01. Welcome Giheon, Changjo and Kyoowon to the lab.

2022-07-25. [My textbook on nonparametric statistics](./books.html) is selected as an excellent academic book by the National Academy of Sciences of the Republic of Korea.

2022-06-23. I gave a public lecture during the KSS conference. The lecture is about "statistics of things that cannot be averaged", and you can find the slides [here](./papers/statistics_public_lecture_2022.pdf). 

2022-05-11. My team and I are selected to receive a three-year research grant on Data Privacy from IITP. The mission is to enhance the use of synthetic data in national database release mechanisms.

2022-04-14. An article introducing the R package [ClusTorus](https://cran.r-project.org/web/packages/ClusTorus/index.html) and its use is accepted for publication in the R journal. Kudos to Seungki!

2022-03-01. [My textbook on nonparametric statistics](./books.html) is now on [sale](https://product.kyobobook.co.kr/detail/S000001762578). This book, written in Korean, is aimed at advanced undergraduate and graduate students who are interested in nonparametric statistics. 

2022-03-01. Welcome Dr. Kipoong Kim to the lab! Dr. Kim from Pusan University will be supported by SSTF and investigate multi-source data analysis. 

2022-01-12. [Closed] I have an opening for a [postdoctoral researcher](./papers/Wanted.html).

2021-11-12. [A research paper](./papers/EJS1945_DDP.pdf) revealing double data piling phenomenon in high dimensional classification, and its relation to negatively ridged classifier, is accepted for publication in *Electronic Journal of Statistics*. This is jointly done with my former student Woonyoung Chang and my collaborator Jeongyoun Ahn. We were looking for a positve optimal ridge parameter, but found that our intuition was wrong! A few more papers will come out in this line of research.

2021-10-26. [Juhee's work](./papers/35(1)-061_dp_histrogram.pdf) on differential privacy is accepted for publication in *Korean Journal of Applied Statistics*. This article is written in Korean, and discusses the use of bootstrap in testing equality of distributions based on privatized histograms. 

2021-09-10. I have received [**Research Award**](./pictures/2021_9_researchaward.PNG) from the College of Natural Science, Seoul National University. Thanks!  

2021-09-01. Welcome Taehyun Kim, a new masters student, Dr. Jongkyeong Kang and Dr. Seung Woo Kwak to the lab. Dr. Kang from Korea Univ. will investigate multi-source data analysis problems (supported by SSTF) and Dr. Kwak from Univ. of Georgia will continue his research on data privacy (supported in part by BK21 and by NRF). 

2021-07-08. After years of waiting, "Uniqueness questions in a scaling-rotation geometry on the space of symmetric positive-definite matrices" is accepted for publication in *Differential Geometry and its Applications*. This manuscript is part II of [the 2017 EJS paper](http://projecteuclid.org/euclid.ejs/1491292817), in which we addressed only 2 x 2 and 3 x 3 matrices. The current paper addresses dimensions $p\ge 4$. The link to this article is [here](https://doi.org/10.1016/j.difgeo.2021.101798).

2021-06-02. An R package [ClusTorus](https://cran.r-project.org/web/packages/ClusTorus/index.html) is available at CRAN. The contents in this package include the functions for the AOAS article (see below), and an improved, and extended, version of mixture model-based clustering for the multivariate angular data. All credits go to Seungki Hong. We are preparing an article introducing this R package and its use. 

2021-03-22. An article discussing clustering the dihedral angles on the torus is accepted for publication in *The Annals of Applied Statistics* (AOAS). This article stems from an undergraduate intern report by Kiho Park. With a help of Dr. Byungwon Kim (now at KNU), the article discusses methods of clustering on the torus, and reveals a difference among the clustering structures of glycoprotein backbone angles from SARS-CoV-2 and those from other strains of coronaviruses.

2021-03-03. [Closed] I have an opening for a [postdoctoral researcher](./papers/Wanted.html), at least one new master's student, and one new master-Ph.D combined student at my lab.

2021-03-03. We have launched a new website for the lab: [https://statlet.github.io](https://statlet.github.io)

2021-01-23. My paper "Geodesic projection of the von Mises-Fisher distribution for projection pursuit of directional data" [(link)](https://projecteuclid.org/journals/electronic-journal-of-statistics/volume-15/issue-1/Geodesic-projection-of-the-von-MisesFisher-distribution-for-projection-pursuit/10.1214/21-EJS1807.full) is accepted for publication in *Electronic Journal of Statistics*. This answers a fundamental question in directional statistics: If a von Mises-Fisher distributed random direction is projected onto a geodesic, it is still von Mises distributed?

2020-12-19. The manuscript ["Covariance-engaged Classification of Sets via Linear Programming"](https://arxiv.org/abs/2006.14831) is accepted for publication in *Statistica Sinica*. This work studies sparse estimations for "set classification" and their theoretical properties. It was conceived by Xingye and myself about five years ago, but a real development began after Zhao joined the team. 

2020-10-19. I, Mark and Steve wrote a response to a letter to the editor in *The Annals of Applied Statistics* (AOAS). The letter comments on the EM algorithm we used in our 2011 AOAS paper. We thought a proper response was due. This letter will appear in AOAS. (It appeared in two months: [Here](http://dx.doi.org/10.1214/20-AOAS1411) is the link.)

2020-10-06. I am selected to receive a prestigious five-year [**research grant from Samsung Science & Technology Foundation**](http://www.samsungstf.org/ssrfPr/researcher/viewResearcher.do?idx=444&pageIndex=1&searchCondition=all&searchKeyword=%EC%A0%95%EC%84%B1%EA%B7%9C&searchResearchProgram=%EA%B8%B0%EC%B4%88%EA%B3%BC%ED%95%99&searchResearchDepth1=&searchResearchDepth2=&searchResearchBelong=&searchResearchSelectYear=&searchResearchState=). The proposed topic is on generalizations of multi-source integrative factor models and statistical inference.

2020-09-22. The manuscript "[Adjusting systematic bias in high dimensional principal component scores](https://doi.org/10.5705/ss.202019.0400)," written by myself is accepted for publication in *Statistica Sinica*. *Statistica Sinica* is notorious for its long interval between the acceptance and print. 

2020-08-30. A video explaining my research interest is on [YouTube](https://www.youtube.com/watch?v=WhlLZix8JPI). This is a part of the CNS series of promoting research agendas. Intended viewers are prospective graduate students. 

2020-08-07. The manuscript "[Covariate-driven factorization by thresholding for multi-block data](https://doi.org/10.1111/biom.13352)" is accepted for publication in *Biometrics*. This work is written by Xing (my former PhD student), Sungwon (again my former PhD student), Gen and myself and is a major part of Xing's doctoral dissertation. 

2020-06-26. The manuscript "Covariance-engaged Classification of Sets via Linear Programming" by Zhao, Xingye and myself is now on [arXiv](https://arxiv.org/abs/2006.14831).

2020-02-20. The manuscript "Kurtosis test of modality for rotationally symmetric distributions on hyperspheres," by Byungwon, Joern and myself, is accepted for publication in *The Journal of Multivariate Analysis*.  [(link)](https://www.sciencedirect.com/science/article/pii/S0047259X19306141) This work is part of Byungwon's PhD dissertation, but changes since then are enormous. The issues addressed and raised in this paper lead to a promising research direction on projection pursuit for directional data. 

2019-09-06. I have received [**Excellence in Teaching Award**](./pictures/2019_9_teaching_award.jpg) from the College of Natural Science. Thanks!

2019-08-08. I am now an associate editor of *Computational Statistics & Data Analysis*.

2019-02-20. I am selected to receive a five-year **mid-career research grant from National Research Foundation**. The proposed topic is on high-dimensional and non-Euclidean statistics. 

2018-12-18. The manuscript "Small sphere distributions for directional data with application to medical imaging" by Stephan, Joern, Byungwon and myself is accepted for publication in  *Scandinavian Journal of Statistics*. [(link)](https://doi.org/10.1111/sjos.12381) This work began its life in 2015 from a query from Steve Marron (Is there a parametric distribution for small-circle behavior of data?). Stephan and I sent a preliminary version of this to a conference, then decided not to publish. Byungwon took over and has created a nice family of distributions on hyperspheres, called "Small sphere distributions". This is a part of his PhD dissertation.

2018-10-30. My contribution to the Korean Statistical Society newsletter is now in print. It's about data science education (from the statistical perspective) and is written in Korean. You can see it [here](http://www.kss.or.kr/bbs/board.php?bo_table=newsletter&wr_id=113) but the online version is only for members.

2018-10-10. As a new faculty member of Seoul National University, I did an interview introducing myself  [(link)](http://science.snu.ac.kr/bbs/view.php?board_id=kor_profnews&idx=311&m=4&gul_no=6817&page=1). 

2018-10-09. The manuscript "Penalized Orthogonal Iteration for Sparse Estimation of Generalized Eigenvalue Problem" by Prfessors Jeon and Ahn, and myself, is accepted for publication in *Journal of Computational and Graphical Statistics*. [(link)](https://doi.org/10.1080/10618600.2019.1568014)

2018-09-01. I have officially joined the department of Statistics at Seoul National University.

# BadNews

2022-11-17. I was not selected to be a member of Young Korean Academy of Science and Technology. Disappointed, but okay. 

2022-05-11. My team and I were not selected to receive a research grant from IITP on an application of differential privacy. In addition, a different team including me was not selected to receive a basic research lab grant from NRF on the statistical foundation of differential privacy. 

2020-10-22. I have decided not to pursue a publication of Lee and Jung (2017). This paper is part of Sungwon's doctoral dissertation, and has been considered for a couple of journals with mixed responses. The work has drawn some attention from researchers (with nontrivial Google Scholar citation numbers). The effort I need to put in to publish this in an established journal outweighs the merit of the paper. This paper will remain as an [arXiv](https://arxiv.org/abs/1603.01775) paper. 
