# NotYetPrinted

Jaesung Park and Sungkyu Jung (2026+), "Generalized Frechet means with random minimizing domains and its strong consistency", accepted for publication in *Biometrika*. [(link)](https://doi.org/10.1093/biomet/asag002) [(arXiv)](https://arxiv.org/abs/2311.10958)

Jongmin Lee and Sungkyu Jung (2025+), "Huber means on Riemannian manifolds," accepted for publication in *Journal of the Royal Statistical Society: Series B*. [(link)](https://doi.org/10.1093/jrsssb/qkaf054) [(arXiv)](https://arxiv.org/abs/2407.15764)

Sujin Lee and Sungkyu Jung (2025+). "Debiased Group Lasso for Multiple Compositional Data," accepted for publication in *Annals of the Institute of Statistical Mathematics*. [(link)](https://link.springer.com/article/10.1007/s10463-025-00956-7)

# Published

Minwoo Kim and Sungkyu Jung (2025), "Robust and Differentially Private Principal Component Analysis," *Statistical Analysis and Data Mining: An ASA Data Science Journal*. 18(6) e70053. [(link)](http://dx.doi.org/10.1002/sam.70053) [(arXiv)](https://arxiv.org/abs/2507.15232) 

Minwoo Kim, Sangil Han, Jeongyoun Ahn and Sungkyu Jung (2025). "Variable selection and basis learning for ordinal classification,"  *Journal of Computational and Graphical Statistics* 34(4) 1432-1445. [(arXiv)](https://arxiv.org/abs/2208.10690) [(link)](https://doi.org/10.1080/10618600.2025.2451680)

Dongsun Yoon and Sungkyu Jung (2025). "Adaptive Reference-Guided Estimation of Principal Component Subspace in High Dimensions," *Stat* 14:e70081 [(link)](https://doi.org/10.1002/sta4.70081)

Sangil Han, Kyoowon Kim and Sungkyu Jung (2025). "Subspace Recovery in Winsorized PCA: Insights into Accuracy and Robustness," Proceedings of The 28th *Int. Conf. Artif. Intell. Statist.*  (AISTATS 2025), PMLR 258:3061-3069 [(arXiv)](https://arxiv.org/pdf/2502.16391) [(pdf)](https://raw.githubusercontent.com/mlresearch/v258/main/assets/han25c/han25c.pdf)

Donghyeok Jo and Sungkyu Jung (2025). "Inference on the shape of densities on Riemannian manifolds via SiZer",  *Journal of Korean Statistical Society*, 54, 442-477. [(pdf)](https://rdcu.be/d6Yh9) [(link)](https://link.springer.com/article/10.1007/s42952-024-00301-3) [(software)](https://github.com/sungkyujung/SiZer_manifold)

Min-Jeong Park and Sungkyu Jung (2025). "Design and Operation of Multi-Party Feature Store (MPFS) for Secure and Privacy-Preserving Data Integration and Utilization," *Journal of The Korean Official Statistics* 30(1) 28-60. [(pdf)](./papers/MPFS.pdf) (This article is written in Korean.) 

Minwoo Kim, Jonghyeok Lee, Seung Woo Kwak, and Sungkyu Jung (2025). "Differentially Private Multivariate Statistics with an Application to Contingency Table Analysis," *Electronic Journal of Statistics* 19(1) 1507-1569.  [(arXiv)](https://arxiv.org/abs/2211.15019) [(link)](https://doi.org/10.1214/25-EJS2368)

Sungkyu Jung, Brian Rooks, David Groisser and Armin Schwartzman (2025).  "Averaging symmetric positive-definite matrices on the space of eigen-decompositions", *Bernoulli*, 31(2), 1552-1578. [(pdf)](./papers/BEJ1783.pdf) [(link)](http://dx.doi.org/10.3150/24-BEJ1783) [(arXiv)](https://arxiv.org/abs/2306.12025)

Kipoong Kim, Jaesung Park, and Sungkyu Jung (2024). "Principal component analysis for zero-inflated compositional data",  *Computational Statistics and Data Analysis* 198, October, 107989. [(link)](https://doi.org/10.1016/j.csda.2024.107989) [(software)](https://github.com/statpng/CompositionalPCA)

Taehyun Kim, Woonyoung Chang, Jeongyoun Ahn, and Sungkyu Jung (2024). "Double Data Piling: A High-Dimensional Solution for Asymptotically Perfect Multi-Category Classification" *Journal of Korean Statistical Society* 53, 704-737. [(link)](https://doi.org/10.1007/s42952-024-00263-6) [(pdf)](https://rdcu.be/dDBld)

Sangil Han, Kyoowon Kim and Sungkyu Jung (2024). "Robust SVD Made Easy: A fast and reliable algorithm for large-scale data analysis," Proceedings of The 27th *Int. Conf. Artif. Intell. Statist.*  (AISTATS 2024), PMLR 238:1765-1773. [(arXiv)](https://arxiv.org/abs/2402.09754) [(pdf)](https://proceedings.mlr.press/v238/han24a/han24a.pdf)

Sujin Lee and Sungkyu Jung (2024). "Variable Selection and Inference Strategies for Multiple Compositional Regression," *Chemometrics and Intelligent Laboratory Systems* 248, May, 105121. [(link)](https://doi.org/10.1016/j.chemolab.2024.105121)

Sangil Han, Minwoo Kim, Sungkyu Jung and Jeongyoun Ahn (2024). "Sparse Ordinal Discriminant Analysis," *Biometrics* 80(1), March, ujad040, [(link)](https://doi.org/10.1093/biomtc/ujad040)

Seung Woo Kwak and Sungkyu Jung (2024). "Highly-private large-sample tests for contingency tables", *Stat* 13:e658 [(link)](https://doi.org/10.1002/sta4.658) [(pdf)](./papers/Highlyprivatetables.pdf)

Kipoong Kim and Sungkyu Jung (2024). "Integrative sparse reduced-rank regression via orthogonal rotation for analysis of high-dimensional multi-source data,"  *Statistics and Computing* 34,    #2. [(link)](https://doi.org/10.1007/s11222-023-10322-3) [(pdf)](https://rdcu.be/doVUF)  [(software)](https://github.com/statpng/iSRRR)

Changjo Yu, Sungkyu Jung and Jisu Kim (2023), "Significance of Modes in the Torus by Topological Data Analysis,"  *Stat*  12:e636 [(link)](https://doi.org/10.1002/sta4.636)

Byungwon Kim, Sungkyu Jung, Johan Lim, and Woncheol Jang (2023). "Comparisons of parametric and non-parametric methods for analyzing RT-PCR experiment data,"  *Chemometrics and Intelligent Laboratory Systems* 242, 104982. [(link)](https://doi.org/10.1016/j.chemolab.2023.104982)

An, S., Doan, T., Lee, J., Kim, J., Kim, YJ., Kim, Y., Yoon, C., Jung, S., Kim, D., Kwon, S., Kim, HJ., Ahn, J., and Park, C. (2023). "A Comparison of Synthetic Data Approaches Using Utility and Disclosure Risk Measures", *The Korean Journal of Applied Statistics* 36(2), 141-166.  [(pdf)](./papers/kjas-23-36-2_141.pdf) (This article is written in Korean.)

Sujin Lee, Sungkyu Jung, Jeferson Lourenco, Dean Pringle, and Jeongyoun Ahn (2023). "Resampling-based Inferences for Compositional Regression with Application to Beef Cattle Microbiomes", *Statistical Methods in Medical Research*, 32(1), 151-164. [(link)](https://journals.sagepub.com/doi/pdf/10.1177/09622802221133550)

Seungki Hong and Sungkyu Jung (2022). "ClusTorus: An R package for prediction and clustering on the torus by conformal prediction", *The R Journal*, 14(2), 186-207. [(link)](https://journal.r-project.org/articles/RJ-2022-032/)

Zhao Ren, Sungkyu Jung and Xingye Qiao (2022). "Covariance-engaged Classification of Sets via Linear Programming",  *Statistica Sinica* 32, 1515-1540. [(link)](https://doi.org/10.5705/ss.202020.0253) [(arXiv)](http://arxiv.org/abs/2006.14831) 

Byungwon Kim, Seonghong Kim, Sungkyu Jung, Woncheol Jang and Johan Lim (2022) "Comments on "Online estimation of the case fatality rate using a run-off triangle data approach: An application to the Korean MERS outbreak in 2015" by Sungim Lee and Johan Lim published in Statistics in Medicine (vol. 38, 2644-2679, 2019)". *Statistics in Medicine* 41(9), 1728-1732. [(link)](http://dx.doi.org/10.1002/sim.9123)

Sungkyu Jung (2022). "Adjusting systematic bias in high dimensional principal component scores", *Statistica Sinica* 32, 939-959.  [(pdf)](./papers/A32n213.pdf)[(arXiv)](https://arxiv.org/abs/1708.05026) [(link)](https://doi.org/10.5705/ss.202019.0400)

Juhee Son, Min-jeong Park and Sungkyu Jung (2022). "A Parametric Bootstrap Test for Comparing Differentially Private Histograms". *The Korean Journal of Applied Statistics* 35(1), 1-17. [(pdf)](./papers/35(1)-061_dp_histrogram.pdf) (This article is written in Korean.)

Woonyoung Chang, Jeongyoun Ahn and Sungkyu Jung (2021). "Double data piling leads to perfect classification". *Electronic Journal of Statistics* 15(2): 6382-6428 [(link)](https://doi.org/10.1214/21-EJS1945)

Sungkyu Jung, Kiho Park and Byungwon Kim (2021). "Clustering on the torus by conformal prediction", *Annals of Applied Statistics*. Vol. 15, No. 4, 1583-1603. [(link)](http://dx.doi.org/10.1214/21-AOAS1459) [(pdf)](papers/AOAS1459.pdf)

Xing Gao, Sungwon Lee, Gen Li and Sungkyu Jung (2021). "Covariate-driven factorization by thresholding for multi-block data", *Biometrics*, 77(3) September, 1011-1023  [(link)](https://doi.org/10.1111/biom.13352) [(software)](https://github.com/sungkyujung/COBS)

David Groisser, Sungkyu Jung and Armin Schwartzman (2021). "Uniqueness questions in a scaling-rotation geometry on the space of symmetric positive-definite matrices."  *Differential Geometry and its Applications*. Volume 79, December, 101798. [(link)](https://doi.org/10.1016/j.difgeo.2021.101798) [(arXiv)](https://arxiv.org/abs/1702.03237)

Sungkyu Jung (2021). "Geodesic projection of the von Mises-Fisher distribution for projection pursuit of directional data", *Electronic Journal of Statistics* 15(1): 984-1033. [(link)](https://doi.org/10.1214/21-EJS1807)

Byungwon Kim, Seonghong Kim, Woncheol Jang, Sungkyu Jung, Johan Lim (2021). "Estimation of the case fatality rate based on stratification for the COVID-19 outbreak,"  *PLoS One*. 16(2): e0246921. [(link)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0246921)  [(medRxiv)](https://www.medrxiv.org/content/10.1101/2020.05.23.20111484v1)  

Sungkyu Jung, Mark Foskey, and J. S. Marron (2020). "Response to `Fitting a folded normal distribution without EM'", *Annals of Applied Statistics*, Vol. 14, No. 4, 2099-2100.  [(link)](http://dx.doi.org/10.1214/20-AOAS1411) [(pdf)](papers/AOAS1411.pdf)

Byungwon Kim, Joern Schulz and Sungkyu Jung (2020). "Kurtosis test of modality for rotationally symmetric distributions on hyperspheres",   *The Journal of Multivariate Analysis*, 178, Article 104603. [(link)](https://www.sciencedirect.com/science/article/pii/S0047259X19306141)

Stephen M Pizer, Junpyo Hong, Jared Vicory, Zhiyuan Liu, JS Marron, Hyo-young Choi, James Damon, Sungkyu Jung, Beatriz Paniagua, Joern Schulz, Ankur Sharma, Liyun Tu and Jiyao Wang (2020). "Object shape representation via skeletal models (s-reps) and statistical analysis"  In *Riemannian Geometric Statistics in Medical Image Analysis* (pp. 233-271). Academic Press. [(link)](https://www.sciencedirect.com/science/article/pii/B9780128147252000145)

Byungwon Kim, Stephan Huckemann, Joern Schulz, and Sungkyu Jung (2019). "Small sphere distributions for directional data with application to medical imaging", *Scandinavian Journal of Statistics*. 46(4) 1047-1071. [(arXiv)](https://arxiv.org/abs/1705.10013) [(link)](https://doi.org/10.1111/sjos.12381)

Sungkyu Jung, Jeongyoun Ahn, and Yongho Jeon (2019). "Penalized Orthogonal Iteration for Sparse Estimation of Generalized Eigenvalue Problem" *Journal of Computational and Graphical Statistics*. 28(3) 710-721. [(link)](https://doi.org/10.1080/10618600.2019.1568014) [(arXiv)](https://arxiv.org/abs/1711.03170) [(Software)](https://github.com/sungkyujung/SparseEIG)

Sandra E Safo, Jeongyoun Ahn, Yongho Jeon and Sungkyu Jung (2018). "Sparse Generalized Eigenvalue Problem for Canonical Correlation Analysis With Application to Integrative Analysis of Methylationand Gene Expression Data"  *Biometrics* 74(4), December, 1362-1371. [(link)](https://doi.org/10.1111/biom.12886) [(arXiv)](https://arxiv.org/abs/1611.01066)

Sungkyu Jung, Myung Hee Lee and Jeongyoun Ahn (2018). "On the number of principal components in high dimensions,"  *Biometrika* 105(2), 389-402. [(pdf)](http://www.stat.pitt.edu/sungkyu/papers/Biometrika-2018-JungLeeAhn-asy010-NPCHD.pdf) [(link)](https://academic.oup.com/biomet/article/105/2/389/4944221?guestAccessKey=560ec4f7-790b-4b15-83ed-5cd47eda23fd)  [(arXiv)](https://arxiv.org/abs/1708.04981)

Sungkyu Jung (2018). "Continuum directions for supervised dimension reduction,"  *Computational Statistics and Data Analysis* 125, 27-43. [(pdf)](http://www.stat.pitt.edu/sungkyu/papers/Continuum_CSDA_2018.pdf) [(arXiv)](https://arxiv.org/abs/1606.05988)

Gen Li and Sungkyu Jung (2017). "Incorporating Covariates into Integrated Factor Analysis of Multi-View Data," *Biometrics* 73 (4), 1433-1442. [(pdf)](http://www.stat.pitt.edu/sungkyu/papers/Li_et_al-2017-Biometrics.pdf) [(Software)](https://github.com/reagan0323/SIFA)

David Groisser, Sungkyu Jung, and Armin Schwartzman (2017). "Geometric foundations for statistics on symmetric positive definite matrices: characterizations of minimal scaling-rotation curves in low dimensions", *Electronic Journal of Statistics*, Vol. 11, No. 1, 1092-1159. [(arXiv)](http://arxiv.org/abs/1602.01187)  [(link)](http://projecteuclid.org/euclid.ejs/1491292817)

Hao Song, Dan Ruan, Wenyang Liu, V. Andrew Stenger, Rolf Pohmann, Maria A. Fernandez Seara, Tejas Nair, Sungkyu Jung, Jingqin Luo, Yuichi Motai, Jingfei Ma, John D. Hazle and H. Michael Gach (2017). "Respiratory motion prediction and prospective correction for free-breathing arterialspin labeled perfusion MRI of the kidneys", *Medical Physics* 44, 962-973. [(link)](https://doi.org/10.1002/mp.12099)

Sungkyu Jung, Armin Schwartman and David Groisser (2015). "Scaling-rotation distance and interpolation of symmetric positive-definite matrices". *SIAM. J. Matrix Anal. & Appl.* 36-3, pp. 1180-1201 [(link)](https://epubs.siam.org/doi/10.1137/140967040) [(arXiv)](http://arxiv.org/abs/1406.3361) [(Software)](papers/SCAROT_SPD.zip)

Benjamin Eltzner, Sungkyu Jung and Stephan Huckemann (2015). "Dimension Reduction on Polyspheres with Application to Skeletal Representations" *Proc. Geometric Science of Information 2015*, Springer LNCS, pp. 22-29. [(link)](http://link.springer.com/chapter/10.1007/978-3-319-25040-3_3)

Joern Schulz, Sungkyu Jung, Stephan Huckemann, Michael Pierrynowski, J. S. Marron, Stephen M. Pizer (2015) "Analysis of rotational motion from directional data". *Journal of Computational and Graphical Statistics*, 24(2), 539-560. [(pdf)](http://www.stat.pitt.edu/sungkyu/papers/rotationSJ.pdf) [(Supplementary Material)](http://www.stat.pitt.edu/sungkyu/papers/SupplementaryMaterialSJ.pdf) [(link)](http://www.tandfonline.com/doi/abs/10.1080/10618600.2014.914947) [(Software)](http://www.stat.pitt.edu/sungkyu/software/estRotDeformation.zip)

Sungkyu Jung and Xingye Qiao (2014). "A statistical approach to set classification by feature selection with applications to classification of histopathology images", *Biometrics*, 70, 536-545.  [(link)](https://onlinelibrary.wiley.com/doi/pdf/10.1111/biom.12164)

Sungkyu Jung and Jason Fine (2013). Comment on "Large Covariance Estimation by Thresholding Principal Orthogonal Complements" by Fan, Liao and Mincheva, *Journal of Royal Statistical Society, Series B*, 75(4), 666-666. [(link)](http://onlinelibrary.wiley.com/doi/10.1111/rssb.12016/abstract)

Stephen M. Pizer, Sungkyu Jung, Dibyendusekhar Goswami, Xiaojie Zhao, Ritwik Chaudhuri, James N. Damon, Stephan Huckemann, J. S. Marron (2013). "Nested Sphere Statistics of Skeletal Models", in *Innovations for Shape Analysis: Models and Algorithms*. M. Breub, Bruckstein and Maragos (Eds), Springer, Berlin, 93-115. [(link)](http://www.springer.com/mathematics/computational+science+%26+engineering/book/978-3-642-34140-3) [(preprint)](http://midag.cs.unc.edu/pubs/papers/SkeletalStats-dagstuhl2011.pdf)

Sungkyu Jung, Arusharka Sen and J. S. Marron (2012). "Boundary behavior in high dimension, low sample size asymptotics of PCA", *The Journal of Multivariate Analysis*, 109, 190-203. [(pdf)](http://www.stat.pitt.edu/sungkyu/papers/JMVA3338-BNDRPCAHDLSS.pdf) [(link)](http://dx.doi.org/10.1016/j.jmva.2012.03.005)

Sungkyu Jung, Ian L. Dryden and J. S. Marron (2012). "Analysis of Principal Nested Spheres", *Biometrika*, 99(3), 551-568. [(pdf)](http://www.stat.pitt.edu/sungkyu/papers/Biometrika-2012-Jung-551-68.pdf) [(Supplementary Material)](http://www.stat.pitt.edu/sungkyu/papers/PNS-OnlineSupplement.pdf) [(link)](http://biomet.oxfordjournals.org/content/early/2012/07/24/biomet.ass022) [(Software-original)](http://www.stat.pitt.edu/sungkyu/software/PNScodes.zip)

Sungkyu Jung (2011). "A Backward Generalization of PCA for Exploration and Feature Extraction of Manifold-Valued Shapes", in *Recent Advances in Functional Data Analysis and Related Topics*, F. Ferraty (Ed), 183-188. [(link)](http://www.springer.com/statistics/book/978-3-7908-2735-4)

Sungkyu Jung, Mark Foskey and J. S. Marron (2011). "Principal Arc Analysis on direct product manifolds", *The Annals of Applied Statistics*, 5, 578-603. [(pdf)](http://www.stat.pitt.edu/sungkyu/papers/AOAS370.pdf)

Sungkyu Jung, Xiaoxiao Liu, J. S. Marron and Stephen M. Pizer (2010). "Generalized PCA via the backward stepwise approach in image analysis", in Brain, Body and Machine: Proceedings of an International Symposium on the 25th Anniversary of McGill University Centre for Intelligent Machines, J. Angeles et al. (Eds.) *Advances in Intelligent and Soft Computing* 83, 111-123. [(pdf)](http://www.stat.pitt.edu/sungkyu/papers/backPCAimage.pdf)

J. S. Marron, Sungkyu Jung and Ian L. Dryden (2010). "Speculation on the Generality of the Backward Stepwise View of PCA," *Proceedings of MIR 2010: 11th ACM SIGMM International Conference on Multimedia Information Retrieval*, Association for Computing Machinery, Inc., Danvers, MA, 227-230. [(pdf)](http://www.stat.pitt.edu/sungkyu/papers/MIR2010FinalP227.pdf)

Sungkyu Jung, Mark Foskey and J. S. Marron (2010), discussion on "Intrinsic shape analysis: Geodesic PCA for Riemannian manifolds modulo isometric lie group actions" by Huckemann S., Hotz T. and Munk A., *Statistica Sinica* 20(1) 63-65. [(pdf)](http://www.stat.pitt.edu/sungkyu/papers/A07-173a.pdf) 

Sungkyu Jung and J. S. Marron (2009). "PCA consistency in High dimension, low sample size context". *The Annals of Statistics* 37, 4104-4130. [(pdf)](http://www.stat.pitt.edu/sungkyu/papers/AOS709.pdf) [(link)](https://projecteuclid.org/euclid.aos/1256303538)

# WorkinProgress

Yongjae Kim, Haeun Moon and Sungkyu Jung. "An Association Measure for Mixed-Types Variables," manuscript. 

Chihoon Lee, Sungkyu Jung and Hyokyung G. Hong. "Predicting current outcomes from historical survey data with weighted conformal prediction," manuscript.  

Jongmin Lee and Sungkyu Jung. "On the Kolmogorov-Feller weak law of large numbers for Frechet mean on non-compact symmetric spaces," manuscript. [(arXiv)](https://www.arxiv.org/abs/2509.02074)

Jongmin Lee and Sungkyu Jung. "General M-estimators of location on Riemannian manifolds: existence and uniqueness," manuscript. [(arXiv)](https://www.arxiv.org/abs/2508.16149)

Kyungjin Shin, Hyunsu Yu, Yongjae Kim, Giheon Seong, Changwon Yoon, Jeongyoun Ahn, Sungkyu Jung and Cheolwoo Park, "A Comprehensive Analysis of Utility and Disclosure Risk Metrics for Synthetic Data," manuscript. 

Minwoo Kim, Junyong Park and Sungkyu Jung, "Enhanced Differentially Private Mechanisms via Empirical Bayes," manuscript. 

David Groisser, Sungkyu Jung, and Armin Schwartzman."A scaling-rotation metric on the space of symmetric positive-definite matrices, I: Existence," manuscript.

Jaesung Park and Sungkyu Jung, "Wasserstein-Quantile PCA", manuscript in progress

Taehyun Kim, Jeongyoun Ahn and Sungkyu Jung. "Optimal Test-Data Piling in HDLSS Classification with Covariance Heterogeneity," manuscript. (An old version is available at [arXiv](https://arxiv.org/abs/2211.15562).)

SeoWon Choi and Sungkyu Jung. "Integrative decomposition of multi-source data by identifying partially-joint score subspaces," manuscript. [(arXiv)](https://arxiv.org/abs/2203.14041)

David Groisser, Sungkyu Jung, and Armin Schwartzman.  "A genericity property of Frechet sample means on Riemannian maniflds", [(arXiv)](https://arxiv.org/abs/2309.13823) [(A video summary by Knowlify)](./visuals/38a06510-202f-49ad-b35b-ddbbc7e22199_combined.mp4)

Minwoo Kim and Sungkyu Jung. "Non-asymptotic error bound for sparse low-rank structured GEP", manuscript.

Sungwon Lee and Sungkyu Jung (2017). "Combined Analysis of Amplitude and Phase Variations in Functional Data"  [(arXiv)](https://arxiv.org/abs/1603.01775)   
