---
title: "Sungkyu Jung"
params:
   address: Department of Statistics, Seoul National University, Building 25 Room 436, 1 Gwanak-ro, Gwanak-gu, Seoul 08826, Korea
   email: sungkyu@snu.ac.kr
   telephone: "+82-2-880-6578"
   website: https://jung.snu.ac.kr/
---


<!--html_preserve-->
<style type="text/css">
ul.CV {
list-style-type: none;
}
</style>
<!--/html_preserve-->
 
```{r echo=FALSE, eval = TRUE}
tmp <- Sys.setlocale("LC_TIME", "C")
```

<ul class="CV">
<li><i class="fa fa-home" aria-hidden="true"></i>  `r paste(" ",params$address)`</li>
<li><i class="fa fa-envelope-o" aria-hidden="true"></i>  `r paste(" ",params$email)`</li>
<li><i class="fa fa-mobile" aria-hidden="true"></i>  `r paste(" ",params$telephone)`</li>
<li><i class="fa fa-globe" aria-hidden="true"></i>  [`r paste(" ",params$website)`](`r params$website`)</li>
<li><i class="fa fa-clock-o" aria-hidden="true"></i> Last Updated: `r paste(" ",format(Sys.Date(), "%B %d, %Y"))`</li>
</ul>



## Education

- Ph.D. in Statistics, University of North Carolina at Chapel Hill. 2006--2011

- B.S. in Statistics, Seoul National University. 1999--2003


## Academic appointments

* Department of Statistics, Seoul National University 
     + Professor, 2022--
     + Associate Professor, 2018--2022.
     
* Institute for Data Innovation in Science, Seoul National University
     + Director, 2024--
     
* Department of Statistics, University of Pittsburgh
     + Associate Professor (tenured), 2017-2018.
     + Assistant Professor, 2011--2017.

     
## Research Interest

- Modern Multivariate Statistics 
- High-dimension, low-sample-size (HDLSS) analysis
- Statistics for unconventional, non-Euclidean, manifold-valued and/or multi-sourced data 
- Data privacy

## Honors 

- Research Award, College of Natural Science, SNU, Sep. 2021.
- Excellence in Teaching Award, College of Natural Science, SNU, Sep. 2019.
- Early Career Development Award, Korean International Statistical Society, 2016.
- US Junior Oberwolfach Fellow, MFO, Germany, 2014.
- Distinguished Paper Award, International Biometric Society/ENAR, 2011.
- Wassily Hoeffding Award, Statistics and Operations Research, University of North Carolina, 2007

## Grants

- PI, NRF RS-2024-00333399, 2024-2029.

- co-I, NRF LAMP project (RS-2023-00301976), 2023-2028. 

- co-PI, NRF Basic Research Lab grant (RS-2023-00218231), 2023-2026. 

- co-PI, IITP R&D grant (2022-0-00937), 2022-2024.

- PI, Samsung Science & Technology Foundation (SSTF-BA2002-03), 2020-2025.

- PI, NRF 2019R1A2C2002256, 2019-2024.

- PI, Internal grant, Seoul National University, 2018-2020.

- PI, dB-SERC, University of Pittsburgh,  2017-2018.

- PI, Central Research Development Fund, University of Pittsburgh, 2016-2018.

- PI, NSF DMS-1307178, 2013-2016.

- PI, Hewlett International Grants, UCIS, University of Pittsburgh, 2012, 2013, 2016.

- Co-I, NIH (NCI) 5R01CA159471-03, 2011-2014.

## Selected Service

- Deputy Director, SNU Center for LAMP Project, 2023.10.01 --
- Associate Editor, Computational Statistics and Data Analysis, 2019-
- Associate Editor, Journal of Nonparametric Statistics, 2017-
- Associate Editor, Journal of Korean Statistical Society, 2014-
<!-- - Associate Liaison to National Institute of Statistical Science, 2015-2018 -->
- Graduate Director, Department of Statistics, University of Pittsburgh, 2017--2018.
<!-- - Elected member, Dietrich School of Arts and Sciences Council, University of Pittsburgh 2016--2019 -->