---
title: "People"
output: html_document
---

### Postdoctoral researchers 

- Dr. [Minwoo Kim](https://sites.google.com/view/mwkim-stat) (Mar. 2025 - Feb. 2026)

- Dr. Changjun Lim, Mar. 2025 -- 

- Dr. Jaesung Park. Sep 2025 -- 

### Graduate students 
 
- Yongjae Kim, Ph.D. student  

- Kyoowon Kim, Ph.D. student

- Giheon Seong, Ph.D. student

- Chihoon Lee, Ph.D. student

- Jaeeun Chang, Ph.D. student

- Jiwoo Kim, Ph.D. student

- Seongjae Cho, Ph.D. student

- Jeehyun Hwang, Ph.D. student

- Wooyeol Kim, Masters student

- Jeehyun Yoo, Masters student

- Yejin Jo, Masters student

- Jeongmin Ko, Masters student

See my lab [website](https://statlet.github.io) about research activities of these students.


## Former members 

- Jaesung Park, Ph.D. 2025. SNU "Sequential Dimension Reduction for Non-Euclidean data and its Strong Consistency", Post-doc at my lab. 

- DongSun Yoon, MS. 2025. SNU. Advanced to PhD program at University of Michigan.

- Soyul Han, Postdoctoral researcher, April 2024 - Feb. 2025. Professor, Hannam University, Daejeon, Korea.

- [Minwoo Kim](https://sites.google.com/view/mwkim-stat), Ph.D. 2025. SNU. "Enhancing statistical utility in private multivariate statistics: Focusing on contingency tables and principal component analysis", currently a postdoctoral researcher at my lab. 

- Yangha Chung, Postdoctoral researcher, Mar. 2024 - Sep. 2024.

- Donghyeok Jo, Ph.D. 2024. SNU. "Advances on Statistical Inferences for Riemannian Manifold-valued Data." Statistician at Samsung SDS.

- Sujin Lee, Ph.D. 2024. SNU. "Variable Selection and Inference Strategies for Compositional Regressions." Statistician at LG Energy Solution.

- Sangil Han, Ph.D. 2024. SNU. "Advances in supervised and unsupervised dimension reduction." Postdoctoral researcher at Texas A&M University. 

- Seung Woo Kwak, Postdoctoral researcher, Sep. 2021 - Feb. 2024. Professor, Sungkonghoe University, Seoul, Korea.

- Kipoong Kim, Postdoctoral researcher, March 2022 - Feb. 2023, Jul.2023 -- Feb. 2024: Professor, Changwon National University, Changwon, Korea

- Taehyun Kim, MS. 2023. SNU. Advanced to PhD program at Columbia University.

- Changjo Yu, MS. 2023. SNU. Placement: LG Electronics.

- SeoWon Choi, Ph.D. 2023. SNU. "Dimension Reduction Methods for Multi-source and Manifold-valued Data". Postdoctoral researcher at School of Medicine, Seoul National University. 
- Seungki Hong, MS. 2022. SNU. Placement: Meritz Fire & Marine Insurance Co., Ltd.

- Jongkyeong Kang, Postdoctoral researcher, Sep. 2021 - Feb. 2022. Professor, Kangwon National University, Chunchun, Korea. 

- Juhee Son, MS. 2022. SNU. Placement: Meritz Fire & Marine Insurance Co., Ltd.

- Woonyoung Chang, MS. 2021. SNU. Advanced to PhD program at Carnegie Mellon University.

- Jae Min Kim, MS. 2020. SNU. Placement: Financial Supervisory Service

- Xing Gao. Ph.D. 2020, Pitt. "Covariate-driven factorization by thresholding for multi-block data". Senior Analyst at BNY Mellon. 

- Brian Rooks. Ph.D. 2018, Pitt. "Statistical analysis of Random symmetric positive-definite matrices via eigen-decomposition". Strategic Consulting Statistician at Statistics & Data Corporation

- Byungwon Kim. Ph.D. 2018, Pitt. "Small sphere distributions and related topics in directional statistics". Professor, Kyungpook National University, Daegu, Korea.

- Sungwon Lee. Ph.D. 2016, Pitt. "Integrative analysis of variation structure in high-dimensional multi-block data". Mathematical statistician, CDER, FDA.
 